backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Tác Phẩm & Bài Viết"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tiêu đề bài viết", name: "title", widget: "string" }
      - { 
          label: "Chuyên mục", 
          name: "category", 
          widget: "select", 
          options: [
            "Thơ Vũ Thiên Kiều", 
            "Tản Văn & Ký", 
            "Góc Bạn Văn", 
            "Lý Luận & Bình Tác Phẩm"
          ] 
        }
      - { label: "Tác giả (Nếu là bài viết của bạn văn)", name: "author", widget: "string", default: "Vũ Thiên Kiều" }
      - { label: "Ngày đăng", name: "date", widget: "datetime" }
      - { label: "Nội dung văn thơ", name: "body", widget: "markdown" }